security:
  encoders:
    AppBundle\Entity\User:
      id: app.password_encoder

  role_hierarchy:
    ROLE_USER: []
    ROLE_RACER: [ROLE_USER]
    ROLE_DECLARANT: [ROLE_USER]
    ROLE_ORGANISATOR: [ROLE_USER]
    ROLE_JUDGE: [ROLE_USER]
    ROLE_ADMIN: [ROLE_USER]
    ROLE_SPECTATOR: [ROLE_USER]
    ROLE_COMMISSIONER: [ROLE_USER]
    ROLE_DEPARTMENT: [ROLE_USER]
    ROLE_LASF_COMMITTEE: [ROLE_USER]
    ROLE_SVO_COMMITTEE: [ROLE_USER]
    ROLE_COMPETITION_CHIEF: [ROLE_USER]
    ROLE_ACCOUNTANT: [ROLE_USER]
    ROLE_CHAIRMAN: [ROLE_USER]
    ROLE_PRESIDENT: [ROLE_USER]
    ROLE_SECRETARY: [ROLE_USER]

  providers:
    app_users:
      entity:
        class: AppBundle:User
        property: email

  access_decision_manager:
    strategy: unanimous

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error)|css|images|js)/
      security: false

    main:
      anonymous: true
      pattern: ^/
      form_login:
        login_path: app_auth_login
        check_path: app_auth_check
        default_target_path: app_dashboard_help
        intention: _app_auth_login
      logout:
        path: app_auth_logout
        target: app_auth_login

  access_control:
    # anonymous access
    - { path: ^/(login|reset|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/music/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/articles/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/profile/[0-9]+$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/media/cache, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/terms, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/privacy-policy, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(judges)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # requires role
    - { path: ^/, role: ROLE_USER }
    - { path: ^/_console, role: ROLE_ADMIN }

